### ISSUE TITLE
Instruction evaluation

### ISSUE THREAD

**Issue by hieu1999210** [cshizhe/HM3DAutoVLN#2]
Hi Shizhe,
I run into an error while training the speaker. It is because your [caption_evaluation](https://github.com/cshizhe/HM3DAutoVLN/blob/5cbb94847c195fc5123af188a4373cd2ea063193/reverie_speaker_src/utils.py#L59)  function refers to the code that is not in this repo. Could you please update this function or point me to the evaluation code if it is already publicly available?

Thanks,
Hieu

**Comment by cshizhe** [comment]
Hi, the caption evaluation codes can be found [here](https://github.com/cshizhe/eval_cap).
